### ISSUE TITLE
Error Debugging in VSCode: Failed to connect on debug port

### ISSUE THREAD

**Issue by SeiferTim** [vshaxe/hashlink-debugger#109]
This happens about 9 out of 10 times when I try to test/debug my project... it started up... maybe a week or two ago? I might eventually be able to debug if I keep hitting 'cancel' and then trying again, but it's frustrating. Nothing shows up in the Debug Console when this happens.

![image](https://user-images.githubusercontent.com/141478/161521637-09ceb3f9-e205-4fc4-893d-6389dbdae331.png)

Not sure why it asks to open the launch.json, but here is mine:
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Build + Debug",
			"type": "lime",
			"request": "launch"
		},
		{
			"name": "Debug",
			"type": "lime",
			"request": "launch"
		},
		{
			"name": "Macro",
			"type": "haxe-eval",
			"request": "launch"
		}
	]
}
```

When I try to debug, this is all that is in my `Terminal`:
```
> Executing task: lime build hl -debug -clean --connect 6000 <


Terminal will be reused by tasks, press any key to close it.
```

...and my `Output`:
```
Haxe language server started
Haxe Path: haxe.exe
Using --server-connect
Haxe connected!
Listening on port 6000
Done.
Haxe server restart requested: DisplayArguments configuration was changed
Haxe Path: haxe.exe
Using --server-connect
Haxe connected!
Restarted Haxe server: DisplayArguments configuration was changed
Done.
Client connected
Client disconnected
Client connected
Client disconnected
```

**Comment by Devyatyi9** [comment]
I have the same error in cli project,
and I don't use additional dependencies.
![](https://i.imgur.com/YPX8h3z.png)
`{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "HashLink/JIT build & debug",
      "type": "hl",
      "hxml": "build-hl.hxml",
      "request": "launch",
      "cwd": "${workspaceFolder}",
      "preLaunchTask": {
        "type": "haxe",
        "args": "active configuration"
      }
    },
    {
      "name": "Haxe interpreter",
      "type": "haxe-eval",
      "request": "launch"
    }
  ]
}
`

**Comment by ncannasse** [comment]
This is a known issue, we're working on a fix

**Comment by ncannasse** [comment]
This was fixed in 1.3.2 that was just published

**Comment by SeiferTim** [comment]
I still have the same problem about 1/5 of the time I try to debug - but the error message is less verbose and just says "failed to connect on debug port" and the same 2 options ("Open Launch.json" & "cancel")

**Comment by ncannasse** [comment]
@SeiferTim are you sure you're on 1.3.2 ?

**Comment by SeiferTim** [comment]
![image](https://user-images.githubusercontent.com/141478/163571154-c5a5176f-3329-457f-8723-358095dd0b82.png)

Yes.

**Comment by SeiferTim** [comment]
Version 1.3.4 - I was excited to see the changelog message "(again) fixed timeout issue when connecting on debug port"
...only to get the error on my first, second, third, and fourth attempt to debug. 
I didn't get it on attempts 5 or 6, and then I got it again on number 7.
This is still pretty common...
I looked in your source code, and it looks like you have a delay of 2000 ms? (2s)
Can you expose that as a setting that the user can change?

**Comment by ncannasse** [comment]
If you edit the delay and increase it, does it work better?
It's weird that hl.exe is taking more than 2s to launch.

Le sam. 30 juil. 2022 à 11:52, Tim I Hely ***@***.***> a
écrit :

**Comment by ncannasse** [comment]
I mean change it manually in adapter.js

Le sam. 30 juil. 2022 à 14:27, Nicolas Cannasse ***@***.***> a
écrit :

**Comment by SeiferTim** [comment]
I changed it to 30000 and it hasn't shown the error yet (a couple dozen builds so-far).
My project is... very large. If that might be a factor.
